### ISSUE TITLE
Play time under the game cover

### ISSUE THREAD

**Issue by gabbre** [darklinkpower/Nova-X#3]
### Feature Description

I love this skin, it's really clean and elegant, but I miss one feature from the previous skin I was using: the ability to replace the game title with playtime under the game cover

attached is a really shitty mockup :)

### Screenshots

![mockup](https://github.com/darklinkpower/Nova-X/assets/21065949/3debc03b-be71-4f30-a21b-fc51e2988ed5)

**Comment by darklinkpower** [comment]
This is already implemented and can be enabled in the ThemeModifier extension settings.

![image](https://github.com/darklinkpower/Nova-X/assets/1389286/680b75f4-811d-483c-8422-0d789cda7694)

By the way, as a side note the correct term to use is "Theme" instead of "Skin" since they are fundamentally different things:

Skin:

> A skin typically refers to the visual appearance or graphical user interface (GUI) of a software application or a website. It is focused on the superficial elements of the user interface, such as colors, fonts, icons, and overall styling. Skins can change the look and feel of the user interface without altering the underlying functionality.

Theme:

> A theme, on the other hand, encompasses a broader set of customization options and can include changes to not only the visual elements but also the layout, behavior, and overall design of the software. Themes can define not only the colors, fonts, and icons but also the arrangement of elements on the screen, the navigation structure, and even the functionality of certain components.
> 
> Unlike skins, themes can involve more substantial modifications to the software's code and structure, as they may affect how the application behaves and how users interact with it.

In summary, skins are primarily concerned with changing the visual appearance, while themes encompass a broader range of customizations that can include visual elements as well as layout, behavior, and functionality changes.

**Comment by gabbre** [comment]
Thank you for the answer and the clarification! English is not my native language and I wasn't aware of the difference between the two terms. It was absolutely not my intention to belittle your work

**Comment by darklinkpower** [comment]
No offense taken don't worry, it's easy to confuse the two. Unless you have some software knowledge it's difficult for people to know they are different and I just thought I could use the opportunity to explain their differences.
